filenameTemplate: "[{rel_group}] {title} - {ep_num} [{suffix}]"
releaseGroup: CR
epNumLength: 2
fileSuffix: SIZEp
videoQuality: max
dubLanguage: eng
mp4mux: false
muxSubs: true
noCleanUp: false
nServer: 1
oldSubs: false
dlSubs: all
proxy: false
proxy_auth: false
proxy_ssp: false
